-- MySQL Script generated by MySQL Workbench
-- Thu Sep 29 15:13:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `idDepartment` INT NOT NULL,
  `Title` MEDIUMTEXT NULL,
  `Description` LONGTEXT NULL,
  `Short Description` LONGTEXT NULL,
  `Link` LONGTEXT NULL,
  `Parent id` INT NULL,
  PRIMARY KEY (`idDepartment`),
  INDEX `is_child_idx` (`Parent id` ASC) INVISIBLE,
  UNIQUE INDEX `Link_UNIQUE` (`Link` ASC) VISIBLE,
  CONSTRAINT `is_child`
    FOREIGN KEY (`Parent id`)
    REFERENCES `mydb`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` INT NOT NULL,
  `Title` MEDIUMTEXT NULL,
  `Short Description` LONGTEXT NULL,
  `Description` LONGTEXT NULL,
  `Stock` INT NULL,
  `IsFeautered` VARCHAR(45) BINARY NULL,
  `InStore` VARCHAR(45) BINARY NULL,
  `Retail Prise` INT NULL,
  `Tax` INT NULL,
  `Discount` INT NULL,
  `DepartmentId` INT NULL,
  PRIMARY KEY (`idProduct`),
  CONSTRAINT `contains`
    FOREIGN KEY (`DepartmentId`)
    REFERENCES `mydb`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Keywords` (
  `idKeywords` INT NOT NULL,
  `Keyword` LONGTEXT NULL,
  PRIMARY KEY (`idKeywords`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `ssn` INT NOT NULL,
  `First Name` MEDIUMTEXT NULL,
  `Last Name` MEDIUMTEXT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(20) NULL,
  `News Checkbox` VARCHAR(45) BINARY NULL,
  PRIMARY KEY (`ssn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Review` (
  `idReview` INT NOT NULL,
  `Content` LONGTEXT NULL,
  `Rating` VARCHAR(45) NULL,
  `ProdId` INT NULL,
  `UserId` INT NULL,
  PRIMARY KEY (`idReview`),
  UNIQUE INDEX `ProdId_UNIQUE` (`ProdId` ASC) VISIBLE,
  UNIQUE INDEX `UserId_UNIQUE` (`UserId` ASC) VISIBLE,
  CONSTRAINT `review`
    FOREIGN KEY (`ProdId`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_review`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`User` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `IdOrder` INT NOT NULL,
  `OrderDate` DATE NULL,
  `LastChange` DATE NULL,
  `Status` VARCHAR(45) NULL,
  `TrackingNum` VARCHAR(64) NULL,
  `Payment` VARCHAR(64) NULL,
  `UserId` INT NULL,
  UNIQUE INDEX `UserId_UNIQUE` (`UserId` ASC) VISIBLE,
  PRIMARY KEY (`IdOrder`),
  CONSTRAINT `ordered`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`User` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_has_Product` (
  `idOrderedProduct` INT NOT NULL,
  `NumberOfProduct` INT NULL,
  `Purcuse Price` INT NULL,
  `OrederId` INT NULL,
  `ProductId` INT NULL,
  PRIMARY KEY (`idOrderedProduct`),
  INDEX `order_idx` (`OrederId` ASC) VISIBLE,
  INDEX `product_idx` (`ProductId` ASC) VISIBLE,
  CONSTRAINT `order`
    FOREIGN KEY (`OrederId`)
    REFERENCES `mydb`.`Order` (`IdOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product`
    FOREIGN KEY (`ProductId`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_Keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_Keywords` (
  `id` INT NOT NULL,
  `Product_idProduct` INT NULL,
  `KeyProd_idKeywords` INT NOT NULL,
  INDEX `fk_Product_has_KeyProd_KeyProd1_idx` (`KeyProd_idKeywords` ASC) VISIBLE,
  INDEX `fk_Product_has_KeyProd_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Product_has_KeyProd_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_KeyProd_KeyProd1`
    FOREIGN KEY (`KeyProd_idKeywords`)
    REFERENCES `mydb`.`Keywords` (`idKeywords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `ssn` INT NOT NULL,
  `Postal code` INT(10) NULL,
  `Addr City` VARCHAR(45) NULL,
  `Addr Street` VARCHAR(45) NULL,
  `Addr Building` VARCHAR(45) NULL,
  PRIMARY KEY (`ssn`),
  CONSTRAINT `Postal code`
    FOREIGN KEY (`ssn`)
    REFERENCES `mydb`.`User` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`email` (
  `ssn` INT NOT NULL,
  `Email Address` VARCHAR(45) NULL,
  PRIMARY KEY (`ssn`),
  CONSTRAINT `email`
    FOREIGN KEY (`ssn`)
    REFERENCES `mydb`.`User` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
